name: Deploy Vue to GitHub Pages

on:
  push:
    branches: [ "main" ]  # 监听 main 分支的推送

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vue 打包后的文件夹名称
          branch: gh-pages # 将编译后的文件推送到这个分支托管